version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      # - run: 
      #     name: Install npm dependencies
      #     command: |
      #       npm run build
      # - run:
      #     name: Run Unit Tests
      #     command: |
      #       ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results 
  diapk :
    docker:
      - image:  circleci/node:12
    steps:
      - checkout
      - run:
          name: deploy to ec2
          command: | 
             ssh -o "StrictHostKeyChecking no"  ubuntu@13.234.35.138 "cd ~/profile-store; git pull; npm install; node app.js"
            # rsync -zvhr -e ssh . ubuntu@13.234.35.138:/home/ubuntu
      - run:
          name: deploy to ec2
          command: | 
            ssh ubuntu@13.234.35.138 'pm2 restart all'
            
workflows:
  build_test:
    jobs:
      - run_tests
      - diapk
      # - build_docker_image
      # - gke_create_cluster
      # - gke_deploy_app:
      #     requires:
      #       - run_tests
      #       - build_docker_image
      #       - gke_create_cluster
      # - smoketest_gke_deployment:
      #     requires:
      #       - gke_deploy_app
      # - approve-destroy:
      #     type: approval
      #     requires:
      #       - gke_create_cluster
      #       - gke_deploy_app
      #       - smoketest_gke_deployment
      # - gke_destroy_cluster:
      #     requires:
      #       - approve-destroy